name: Deploy Frontend
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t aa122aa/learnDocker -f Dockerfile.dev .
      - run: docker run -e CI=true aa122aa/learnDocker npm test
